name: Nuclei - Vulnerability Scan

on:
    #schedule:
    #  - cron: "13 12 * * 1" # At 12:13 on Monday UTC time (8:13 AM EST)
    workflow_dispatch:

jobs:

  nuclei-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@v3
        with:
          config: |
            target: 
            - https://jester.social
            id:
            - ssh-auth-methods
            - tls-version
            - rails-debug-mode
            - ssl-issuer
            - http-missing-security-headers
            user-agent: "User-Agent:'Nuclei - Vulnerability Scan'"
            sarif-export: nuclei.sarif
            github-report: true
            github-token: ${{ secrets.GITHUB_TOKEN }}

# OPTIONAL
# Below uploads results to the security dashboard
# Requires a public repo, or GHAS
      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v4
        if: success()
        with:
          sarif_file: nuclei.sarif
          category: nuclei-results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
