name: Nuclei - Vulnerability Scan

on:
    #schedule:
    #  - cron: "13 12 * * 1" # At 12:13 on Monday UTC time (8:13 AM EST)
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@v3
        with:
          target: https://jester.social
          flags: "-id ssh-auth-methods -id tls-version -id rails-debug-mode -id rdap-whois -id ssl-issuer -id http-missing-security-headers"
          user-agent: "User-Agent:'Nuclei - Vulnerability Scan'"
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

# Below uploads results to the security dashboard
# Requires a public repo, or GHAS
      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
